<?php

$Printer = NULL;

$Printer = function($Struct, $StructLevel, $Level=1) use(&$Printer) {

	if($Struct instanceof Nether\Senpai\Struct\NamespaceObject) {
		echo "<ul>\n";
		echo "\t<li><a href=\"{$Struct->GetRelativePath($StructLevel,$Struct->GetRenderFilename('html'))}\">{$Struct->GetNameShort()}</a></li>\n";

		foreach($Struct->GetClasses() as $Child)
		$Printer($Child,$StructLevel,($Level+1));

		foreach($Struct->GetNamespaces() as $Child)
		$Printer($Child,$StructLevel,($Level+1));

		echo "</ul>\n";
	}

	if($Struct instanceof Nether\Senpai\Struct\ClassObject) {
		echo "<ul>\n";
		echo "\t<li><a href=\"{$Struct->GetRelativePath($StructLevel,$Struct->GetRenderFilename('html'))}\">{$Struct->GetNameShort()}</a></li>\n";
		echo "</ul>\n";
	}

};

$Printer($surface->Get('Root'),$surface->Get('Level'));
