<!doctype html>
<html>
<head>
	<title><?php $surface->Show('page-title') ?></title>
	<link rel="stylesheet" type="text/css" href="<?php $surface->Show('path-backpedal') ?>design.css" />
</head>
<body>

<div id="header" class="construct"><div>
	<h1><?php echo Nether\Option::Get('app-name') ?></h1>
</div></div>

<div id="main" class="construct"><div>
	<div class="left">
		<div class="contentbox">
<?php $surface->Show('stdout') ?>
		</div>
	</div>
	<div class="right">
<?php $surface->Area('sidebar') ?>
	</div>
</div></div>



</body>
</html>