<?php

$class = $surface->Get('class');

$properties = array_merge($class->Properties,$class->StaticProperties);
$methods = array_merge($class->Methods,$class->StaticMethods);

?>
<div class="class">
	<h1 class="name"><?php echo $class->Name ?></h1>
	<div class="desc">
<?php echo \Michelf\MarkdownExtra::defaultTransform($class->Description), PHP_EOL; ?>
	</div>

	<h2>Properties</h2>

<?php
if(count($properties)) { foreach($properties as $prop) {
	$surface->Set('property',$prop);
	$surface->Area('property');
} } else echo '<div class="desc">This class has no properties.</div>';
?>

	<h2>Methods</h2>

<?php
if(count($methods)) { foreach($methods as $meth) {
	$surface->Set('method',$meth);
	$surface->Area('method');
} } else echo '<div class="desc">This class has no methods.</div>';
?>

</div>
