<?php

use \Nether\Senpai\ClassMember as CM;
$class = $surface->Get('class');

?>

<div class="class">
	<h1 class="name"><?php echo $class->Name ?></h1>
	<div class="desc">
<?php echo $class->ParseInfo(), PHP_EOL; ?>
	</div>

	<div class="members public">
		<h2>Public Properties</h2>
<?php
$surface->Set('properties',$class->FilterMembers((CM::IsPublic),(CM::IsStatic|CM::IsMethod)));
$surface->Area('properties');
?>

		<h2>Public Methods</h2>
<?php
$surface->Set('methods',$class->FilterMembers((CM::IsPublic),(CM::IsStatic|CM::IsProperty)));
$surface->Area('methods');
?>

	</div>
</div>
