<?php

$methods = $surface->Get('methods');

$Datatypes = function($str) {
	return preg_replace(
		'/\b(int|integer|str|string|bool|boolean|float|double|array|object|mixed|void|default(?: [^,\)]+)?)\b/',
		'<span class="datatype">\1</span>',
		$str
	);
}

?>

<?php if(count($methods)) { foreach($methods as $m) { ?>
	<dl id="method-<?php echo strtolower($m->Name) ?>" class="method <?php echo $m->GetInfoTagString(' ',['static','public','protected','private']) ?>">
	<?php foreach($m->GetTag('argv') as $argkey => $argv) { ?>
	<dt>
		<span class="tag return"><?php echo $m->GetTag('return') ?></span>
		<span class="tag access"><?php echo $m->GetTag('access') ?></span>
		<?php foreach($m->GetInfoTags() as $tag => $tval) { ?>
		<span class="tag <?php echo $tag ?>" title="<?php echo htmlentities($tval) ?>"><?php echo $tag ?></span>
		<?php } ?>
		<a href="#method-<?php echo strtolower($m->Name) ?>"><?php echo(($m->HasTag('static'))?('::'):('->')) ?><span class="name"><?php echo $m->Name ?></span>(<span class="argv"><?php echo $Datatypes($argv) ?></span>);</a>
	</dt>
	<?php } ?>
	<dd><?php echo $m->GetInfoParsed() ?></dd>
	</dl>
<?php } } else { ?>
	<div class="empty">This class has no methods.</div>
<?php } ?>

