<?php

$p = $surface->Get('property');

?>

<div class="property <?php echo (($p->Static)?('static'):($p->Access)) ?>">
	<h3>
		<span class="access"><?php echo (($p->Static)?('static'):($p->Access)) ?></span>
		<span class="type"><?php echo $p->Type ?></span>
		<span class="name">$<?php echo $p->Name ?></span>
	</h3>

	<div class="desc">
<?php echo \Michelf\MarkdownExtra::defaultTransform($p->Description), PHP_EOL, PHP_EOL; ?>
	</div>

</div>
