<?php

$Link = function($name) use($surface) {
	return sprintf(
		'%s%s.html',
		$surface->Get('path-backpedal'),
		strtolower(str_replace('\\','/',$name))
	);
}

?>

<div class="contentbox">
	<dl>
		<dt>Main</dt>
		<dd><a href="<?php $surface->Show('path-backpedal') ?>index.html">Home</a></dd>
	</dl>
	<dl>
		<dt>Classes</dt>
<?php foreach(Nether\Stash::Get('code-index') as $class) { ?>
		<dd><a href="<?php echo $Link($class->Name) ?>"><?php echo $class->Name ?></a></dd>
<?php } ?>
	</dl>
</div>
