<html>
<head>
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Roboto+Condensed" />
	<style type="text/css">
		*
		{ box-sizing: border-box; font-family: 'Roboto', sans-serif; }

		html,body
		{ margin: 0px; padding: 0px; }

		h1, h2, h3, h4
		{ line-height: normal; margin: 0px 0px 16px 0px; padding: 0px; }

		.FloatClear
		{ border: 0px; clear: both; }

		.PageHeader
		{ background: #bbb; padding: 10px; }

		.PageFooter
		{ background: #bbb; padding: 10px; }

		.PageTwoCol
		{ width: 100%; }

		.PageTwoCol > div:nth-child(1)
		{ background: #ccc; float: left; padding: 10px; width: 25%; }

		.PageTwoCol > div:nth-child(2)
		{ background: #ddd; float: right; padding: 10px; width: 75%; }

	</style>
</head>
<body>

<div class="PageHeader">
	Senpai Doc
</div>

<div class="PageTwoCol">
	<div>
<?php echo $surface->GetArea('page/sidebar') ?>

	</div>
	<div>
<?php echo $surface->Get('stdout') ?>

	</div>

	<hr class="FloatClear" />
</div>

<div class="PageFooter">
	[footer]
</div>

</body>
</html>